@startuml A3
(*) --> "В навігаційному меню обрати 'View Flights'"
--> "Натиснути на авіарейс зі списку"
if "Дія" then
    -->[переглянути](*)
else
    -->[змінити] "Внести зміни"
    --> "Натиснути кнопку 'Save'"
    if "Зміни коректні" then
        -->[так](*)
    else
        -->[ні] "Внести зміни"
    endif
else
    -->[видалити] "Натиснути кнопку 'Delete'"
    --> "Переглянути повідомлення про успішність операції"
    -->(*)
endif
@enduml