@startuml A4
(*) --> "В навігаційному меню обрати 'View Flights'"
--> "Натиснути кнопку 'Add'"
--> "Ввести інформацію"
--> "Натиснути кнопку 'Save'"
if "Дані коректні" then
    -->[так](*)
else
    -->[ні] "Ввести інформацію"
endif

@enduml