@startuml AU3

!o = "Оплатити online"

(*) --> "Здійснити пошук авіарейсів"
--> "Переглянути повну інформацію про авірейс"
--> "Натиснути кнопку 'Order Ticket'"
--> "Обрати клас, вказати кількість квитків, додати коментар"
--> "Натиснути кнопку 'Choose Payment Method'"
if o then 
    if "Використати бонуси" then
        -->[ні] "Обрати 'Pay All with Credit Card'"
        -->"Ввести дані карти"
        -->"Зачекати результат запиту"
    else
        -->[так] "Обрати 'Pay with Bonuses'"
        -->"Ввести кількість бонусів"
        if "Кількість допустима" then
            -->[ні] "Ввести кількість бонусів"
        else
            -->[так] "Ввести дані карти"
        endif
    endif

else
    -->[ні] "Обрати 'Pay offline'"
    --> "Зачекати результат запиту"  
endif

if "Запит успішний" then
    -->[так] "Отримати інформацію про замовлення"
    --> (*)
else
    -->[ні] "Отримати інформацію про помилку"
    if "Спробувати ще раз" then
        -->[так] "Натиснути кнопку 'Choose Payment Method'"
    else
        -->[ні] (*)
    endif
endif

@enduml