@startuml AU4

(*)--> "Натиснути кнопку 'Profile' у горизонтальній навігаційній панелі"
--> "З випадаючого меню обрати 'Profile Info'"
--> "Переглянути інформацію"
if "Змінити" then
    -->[так] "Ввести нову інформацію"
    if "Вона коректна" then
        -->[так] "Натиснути кнопку 'Зберегти'"
        --> (*)
    else
        -->[ні] "Ввести нову інформацію"
    endif
else
    -->[ні] (*)
endif
@enduml