@startuml AU8

(*)--> "Натиснути кнопку 'Profile' у горизонтальній навігаційній панелі"
--> "З випадаючого меню обрати 'Profile Info'"
--> "Натиснути кнопку 'Delete Profile'"
if "Впевнені" then
    -left->[так] "Натиснути кнопку 'Yes'"
    --> (*)
else
    -right->[ні] "Натиснути кнопку 'No'"
    --> "Натиснути кнопку 'Delete Profile'"
endif

@enduml