@startuml NU3
(*) --> "Відкрити сайт"
--> "Натиснути кнопку 'Sign Up' у горизонтальній навігаційній панелі"
--> "Ввести необхідну інформацію"
--> "Натиснути кнопку 'Sign Up'"
if "Дані коректні" then
    -->[так](*)
else
    -->[ні] "Ввести необхідну інформацію"
endif

@enduml