@startuml NU4
(*) --> "Відкрити сайт"
--> "Натиснути кнопку 'Log In' у горизонтальній навігаційній панелі"
--> "Ввести пошту та пароль"
--> "Натиснути кнопку 'Log In'"
if "Дані коректні" then
    -->[так](*)
else
    -->[ні] "Ввести пошту та пароль"
endif

@enduml