= [[entity_root.anchor]]Розробка та тестування системи "Аеропорт"
:title-page:
Цубін Софія
0.1, 
:short-title: Dev&Test
:toc:
:toclevels: 3
:sectnums:

.Історія змін
[width="100%", options="header"]
|=====================================
|Дата|Версія|Опис|Автор

a|8.12.2021
a|0.1
a|Початкове створення
a|Цубін Софія

|=====================================

== Результати розробки Веб-застосунку

== Модульні тести на підтримку критичного варіанту використання AU1. Придбання або бронювання квитка

== Тести функцій Веб-застосунку на підтримку критичного варіанту використання AU1. Придбання або бронювання квитка

Вважаємо, що в тестах, що не перевірють авторизованість користувача, користовач є авторизованим.

.Тести функцій Веб-застосунку на підтримку критичного варіанту використання
[width="100%", options="header"]
|=====================================
|Функція, що перевіряється|Дії для перевірки|Очікувана реакція сайту|On-line інструмент

a|Авторизованість користувача
a|Авторизований користувач натискає кнопку Buy Tickets
a|Відображення інтерфейсу формування замовлення
a|Selenium

a|Авторизованість користувача
a|Неавторизований користувач натискає кнопку Buy Tickets
a|Перехід до сторінки, що повідомляє про необхідність авторизації
a|Selenium

a|Формування замовлення
a|Користувач обирає клас, вводить коректну кількість квитків, натискає кнопку Pay
a|Відображення інтерфейсу для вибору методу оплати
a|Selenium

a|Формування замовлення
a|Користувач вводить некоректну кількість квитків, натискає кнопку Pay
a|Поточний інтерфейс формування замовлення повідомляє про невалідність даних
a|Selenium

a|Вибір способу оплати - онлайн оплата
a|Користувач натискає Pay Online
a|Редірект на сторінку для оплати
a|Selenium

a|Вибір способу оплати - онлайн оплата з бонусами
a|Користувач, що має доступні бонуси, натискає кнопку Pay Online with Bonuses
a|Відображення інтерфейсу для використання бонусів
a|Selenium

a|Вибір способу оплати - онлайн оплата з бонусами
a|Користувач, що не має доступних бонусів, хоче натиснути на кнопку Pay Online with Bonuses
a|Її немає в інтерфейсі
a|Selenium

a|Вибір способу оплати - офлайн оплата
a|Користувач натискає кнопку Pay Offline
a|Перехід на сторінку, що містить інформацію про замовлення
a|Selenium

a|Вибір способу оплати - користувач передумав його вибирати
a|Користувач натискає кнопку Cancel
a|Повернення до інтерфейсу формування замовлення
a|Selenium

a|Вибір способу оплати - помилка
a|Користувач натискає одну з кнопок для оплати
a|Перехід на сторінку, що сповіщає про помилку з можливістю повернутися до формування замовлення 
a|Selenium

a|Використання бонусів
a|Користувач вводить коректну кілкість бонусів та натискає кнопку Pay
a|Редірект на сторінку для оплати
a|Selenium

a|Використання бонусів
a|Користувач вводить некоректну кількість бонусів (від'ємну)
a|Поле автоматично встановить 0
a|Selenium

a|Використання бонусів
a|Користувач вводить некоректну кількість бонусів (пусте значення) та натискає кнопку Pay
a|Пусте поле прирівнюється до 0. Редірект на сторінку для оплати
a|Selenium

a|Використання бонусів
a|Користувач вводить некоректну кількість бонусів (більше доступних або допустимих)
a|Поле автоматично встановить максимальне допустиме значення
a|Selenium

a|Оплата
a|Користувач вводить коретні дані для оплати
a|Підтвердження оплати. Редірект на сторінку з інформацією про замовлення
a|Selenium

a|Помилка оплата
a|Користувач вводить некоретні дані для оплати
a|Сервіс оплати повідомляє про помилку
a|Selenium

a|Помилка оплата
a|Користувач вводить коректні дані
a|Редірект на сторінку з інформацією про помилку
a|Selenium

|=====================================

== Інші види тестування Веб-застосунку

=== Тестування HTML-коду, каскадних таблиць стилів і Java-скриптів

=== Тестування вигляду Веб-застосунку в передбачених браузерах