@startuml plain

agent User
agent Order
agent OrderHistory
agent Airport
agent Flight
agent Payment
agent Ticket
agent AdminServer
agent AuthServer
agent Bonus
agent Status
agent Search
agent SearchHistory

Order        --o OrderHistory
Order        --o Payment
Flight       --o Order
Ticket       --o Order
Flight       --o Search
User         --- Search
Status       --o Flight
User         --o Order
AuthServer   --- User
AdminServer  --- Flight
AdminServer  --- User
AdminServer  --- Order
Bonus        --o User
Bonus        --o Payment
Search       --o SearchHistory
Airport      --- AdminServer

@enduml
