@startuml plain

agent User
agent Order
agent OrderHistory
agent Airport
agent Flight
agent Payment
agent Ticket
agent AdminServer
agent AuthServer
agent PaymentServer
agent Bonus
agent Search

Order        --o OrderHistory
Order        --o Payment
Flight       --o Order
Ticket       --o Order
Flight       --o Search
User         --- Search
User         --o Order
AuthServer   --- User
AdminServer  --- Flight
AdminServer  --- User
AdminServer  --- Order
Bonus        --o User
Bonus        --o Payment
Airport      --- AdminServer
Payment      --- PaymentServer

@enduml
