apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  selector:
    matchLabels:
      app: admin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - image: docker.shlyahdomrii.tech/admin:latest
        name: admin
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 16Mi
            cpu: 100m
        env:
        - name: FLASK_APP
          value: back.admin
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: admin
              key: DATABASE
        - name: BASIC_AUTH_USERNAME
          value: admin
        - name: BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: admin
              key: PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: admin
              key: SECRET_KEY
        ports:
        - name: http
          containerPort: 5000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Secret
metadata:
  name: admin
type: Opaque
data:
  DATABASE: bXlzcWwrcG9vbDovL2FkbWluOkFkbWluRGV2UEAkJEBteXNxbDozMzA2L2FpcnBvcnQ=
  PASSWORD: QWRtaW5QQCQkdzByZA==
  SECRET_KEY: cmhiYSlKNC0uWzV6KSQ6LXR9Z0J2VC5RW3I3WQ==
