apiVersion: v1
kind: Service
metadata:
  name: gotrue
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: gotrue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotrue
spec:
  selector:
    matchLabels:
      app: gotrue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gotrue
    spec:
      containers:
      - image: docker.shlyahdomrii.tech/gotrue:latest
        name: gotrue
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 16Mi
            cpu: 100m
        env:
        - name: GOTRUE_SITE_URL
          value: https://shlyahdomrii.tech
        - name: GOTRUE_API_HOST
          value: 0.0.0.0
        - name: PORT
          value: '8080'
        - name: GOTRUE_DB_DRIVER
          value: mysql
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: gotrue
              key: DATABASE_URL
        - name: GOTRUE_OPERATOR_TOKEN
          valueFrom:
            secretKeyRef:
              name: gotrue
              key: OPERATOR_TOKEN
        - name: GOTRUE_JWT_EXP
          value: '604800'
        - name: GOTRUE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: gotrue
              key: JWT_SECRET
        - name: GOTRUE_SMTP_HOST
          value: smtp
        - name: GOTRUE_SMTP_PORT
          value: '587'
        - name: GOTRUE_SMTP_ADMIN_EMAIL
          value: noreply@shlyahdomrii.tech
        - name: GOTRUE_LOG_LEVEL
          value: DEBUG
        - name: GOTRUE_MAILER_AUTOCONFIRM
          value: 'true'
        ports:
        - name: http
          containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Secret
metadata:
  name: gotrue
type: Opaque
data:
  DATABASE_URL: Z290cnVlOkdvVHJ1ZURldlBAJCRAdGNwKG15c3FsOjMzMDYpL2dvdHJ1ZT9wYXJzZVRpbWU9dHJ1ZSZtdWx0aVN0YXRlbWVudHM9dHJ1ZQ==
  JWT_SECRET: cERBak1RcDJCU1lrYWtuWk1hVHhDRTU0Vw==
  SMTP_PASSWORD: R29UcnVlRGV2UEAkJA==
  OPERATOR_TOKEN: JyRbfUw3VmsjQj52JGY9XDxkR3RSRl5OYjR9RTlZdnspclg=
