apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  selector:
    matchLabels:
      app: payment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - image: docker.shlyahdomrii.tech/back:v1
        name: payment
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 16Mi
            cpu: 100m
        env:
        - name: FLASK_APP
          value: back.payment
        - name: SITE_URL
          value: http://localhost:3000
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              name: payment
              key: STRIPE_API_KEY
        ports:
        - name: http
          containerPort: 5000
        imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Secret
metadata:
  name: payment
type: Opaque
data:
  STRIPE_API_KEY: c2tfdGVzdF81MUsxZWZiQ1ZFUEt3V3JjUXNSeXpEejdyVHVNUkJkeWNhbHVmelhLQlRGMnBnM0NVdlN4TWJpejdjSG1XYkRDWUhjMExQSTExeWJpRjd0ZmxOaFREb0VxWDAwTVVPYno2UWs=
