# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestToomuchbonuses():
  def setup_method(self):
    self.driver = webdriver.Firefox(executable_path="./drivers/geckodriver")
    self.vars = {}

  def teardown_method(self):
    self.driver.quit()

  def test(self):
    self.driver.get("http://localhost:3000/view/14")
    self.driver.set_window_size(1049, 855)
    time.sleep(2)
    self.driver.find_element(
        By.CSS_SELECTOR, "#view-buy-button > .MuiButton-label").click()

    time.sleep(2)
    self.driver.find_element(By.ID, "order-quantity").send_keys("2")
    self.driver.find_element(By.ID, "order-quantity").click()
    element = self.driver.find_element(By.ID, "order-quantity")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(
        By.CSS_SELECTOR, "#order-choose-pm > .MuiButton-label").click()
    self.driver.find_element(
        By.CSS_SELECTOR, "#order-dialog-p-bonuses > .MuiButton-label").click()

    time.sleep(2)
    self.driver.find_element(By.ID, "bonuses-amount").send_keys("5000")
    self.driver.find_element(By.ID, "bonuses-amount").click()

    time.sleep(7)

  def run_test(self, name):
    self.setup_method()
    self.test()
    self.teardown_method()
    print(name, 'SUCCESS')


TestToomuchbonuses().run_test('Trying to use too much Bonuses')
