# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self):
    self.driver = webdriver.Firefox(executable_path="./drivers/geckodriver")
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1024, 979)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiBox-root-14 .MuiButton-label").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("test@example.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("TestP@$$")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()

  def run_test(self, name):
    self.setup_method()
    self.test()
    self.teardown_method()
    print(name, 'SUCCESS')


TestLogin().run_test('Login')
