@startuml A2
(*) --> "Обрати елемент зі списку"
if "Дія" then
    -->[переглянути](*)
else
    -->[змінити] "Внести зміни"
    if "Зміни коректні" then
        -->[так]"Зберегти"
        --> (*)
    else
        -left->[ні] "Внести зміни"
    endif
else
    -->[видалити] "Натиснути кнопку 'Delete'"
    --> "Переглянути повідомлення про успішність операції"
    -->(*)
endif
@enduml