@startuml A4
(*) --> "В навігаційному меню натиснути на кнопку 'Add Flight'"
--> "Ввести інформацію"
if "Дані коректні" then
    -->[так]"Зберегти"
    --> (*)
else
    -left->[ні] "Ввести інформацію"
endif

@enduml