@startuml AU2

!o = "Оплатити online"

(*) --> "Здійснити пошук авіарейсів"
--> "Переглянути повну інформацію про авіарейс"
if "Переглянутий рейс влаштовує" then
    -->[ні]"Здійснити пошук авіарейсів"
else
    -->[так]"Обрати клас, вказати кількість квитків, додати коментар"
endif

--> "Обрати спосіб оплати"
if o then 
    if "Використати бонуси" then
        -->[ні] "Обрати оплату картою"
        -->"Ввести дані карти"
        -->"Зачекати результат запиту"
    else
        -->[так] "Обрати оплату з використанням бонусів"
        -->"Ввести кількість бонусів"
        if "Кількість допустима" then
            -->[ні] "Ввести кількість бонусів"
        else
            -->[так] "Ввести дані карти"
        endif
    endif

else
    -->[ні] "Обрати оплату в касі"
    --> "Зачекати результат запиту"  
endif

if "Запит успішний" then
    -->[так] "Отримати інформацію про замовлення"
    --> (*)
else
    -->[ні] "Отримати інформацію про помилку"
    if "Спробувати ще раз" then
        -->[так] "Обрати спосіб оплати"
    else
        -->[ні] (*)
    endif
endif

@enduml