@startuml AU4

(*)--> "За допомогою навігаційної панелі відкрити одну зі сторінок з інформацією про профіль"
--> "Переглянути інформацію"
if "Можна змінити" then
    if "Хочеться змінити" then
        -->[так] "Ввести нову інформацію"
        if "Вона коректна" then
            -->[так] "Зберегти"
            --> (*)
        else
            -->[ні] "Ввести нову інформацію"
        endif
    else
        -->[ні] (*)
    endif
else
    -->[ні] (*)
endif
@enduml