@startuml NU1
(*) --> "Відкрити сайт"
--> "Вказати параметри, що цікавлять"
--> "Натиснути кнопку 'Пошук'"
--> "Натиснути на авіарейс зі списку знайдених для перегляду детальної інформації"
--> (*)

@enduml