@startuml NU2
(*) --> "Відкрити сайт"
--> "Натиснути кнопку 'Sign Up' у навігаційній панелі сайту"
--> "Ввести необхідну інформацію"
if "Дані коректні" then
    -->[так]"Створити профіль з вказаними даними"
    --> (*)
else
    -left->[ні] "Ввести необхідну інформацію"
endif

@enduml