@startuml NU3
(*) --> "Відкрити сайт"
--> "Натиснути кнопку 'About Us' у навігаційній панелі"
if "Дізнатися ще більше" then
    -->[так]"Переглянути контактну інформацію аеропорту"
    --> "Написати на вказану пошту або подзвонити"
    --> (*)
else
    -->[ні] (*)
endif
@enduml