
= [[entity_root.anchor]]Специфікація вимог до системи: Інформаційна система "Аеропорт"
:title-page:
Осока Данііл <osokadania@gmail.com>
0.1, 
:short-title: SRS
:toc:
:toc-title: Зміст
:toclevels: 5
:sectnums:


.Історія змін
[width="100%", options="header"]
|=====================================
|Дата|Версія|Опис|Автор

a|20.10.2021
a|0.1
a|Початкове створення
a|Осока Данііл
|=====================================

== Введення

=== Ціль

Ціль цього документу - сформулювати вимоги до інформаційної системи "Аеропорт". Дані вимоги описані в формі прецендентів, коротких описів функціональних вимог і опису нефункціональних вимог.

=== Сфера охоплення
Документ фіксує детальні вимоги до інформаційної системи "Аеропорт" для їх однозначного розуміння всіма учасниками розробки системи.

=== Визначення, акроніми та скорочення
.Визначення, акроніми та скорочення
[width="100%", options="header"]
|=====================================
|Термін|Визначення

|=====================================

=== Посилання
Вимоги співвласників та бачення продукту наявні в документі "Технічне завдання" (TR.pdf).

=== Короткий опис системи

Інформаційна система "Аеропорт" - система, призначена для автоматизації роботи відділу продаж квитків на рейси аеропорту.

== Загальний опис

=== Огляд прецендентів

Короткий опис акторів системи:

.Актори системи
[width="100%", options="header"]
|=====================================
|Актор|Короткий опис 

a|Неавторизований користувач
a|Рядовий користувач системи, що не пройшов авторизацію. Має можливість переглянути список доступних рейсів, знайти або відфільтрувати рейси за певним набором критеріїв. Може зареєструватися в системі або/та пройти авторизацію. 

a|Авторизований користувач
a|Рядовий користувач системи, що пройшов авторизацію. Має такі самі можливості, що і неавторизований користувач, а також може придбати онлайн або забронювати квиток, має можливість переглядати історію своїх польотів і заброньовані квитки, а також може перешлядати і використовувати для накопичені бонуси.

a|Адміністратор
a|Адмініструє систему. Має можливість додавати, коректувати і видаляти інформацію про авіарейси і про користувачів.

|=====================================

Список варіантів використання:

.Реєстр варіантів використання
[width="100%", options="header"]
|=====================================
|Код|Основний актор|Найменування|Суть

a|U1
a|Неавторизований користувач / Авторизований користувач
a|Пошук авіарейсів за параметрами
a|За необхідності отримати список авіарейсів з певними параметрами, користувач може використати функцію пошуку авіаквитків.

a|U2
a|Неавторизований користувач / Авторизований користувач
a|Отримання інформації по авіарейсу
a|Користувач може отримати повну інформацію по конкретному авіарейсу.

a|NU1
a|Неавторизований користувач
a|Реєстрація
a|Неавторизований користувач має можливість пройти процедуру реєстрації в системі.

a|NU2
a|Неавторизований користувач
a|Авторизакія
a|Неавторизований користувач має можливість пройти процедуру авторизації в системі.

a|AU1
a|Авторизований користувач
a|Придбання або бронювання квитка
a|Авторизований користувач може забронювати квиток на обраний авіарейс, при цьому він має можливість або повністю оплатити квиток онлайн, або оплатити бронь пізніше в касі. Також користувач може використовувати бонуси як для повної, так і для часткової оплати квитків.

a|AU2
a|Авторизований користувач
a|Деавторизація
a|Авторизований користувач має можливість пройти процедуру деавторизації в системі.

a|AU3
a|Авторизований користувач
a|Редагування профілю
a|Авторизований користувач має можливість додавати, змінювати власну інформацію, а також видаляти ту власну інформацію, яка вона не є обов'язковою.

a|AU4
a|Авторизований користувач
a|Видалення профілю
a|Авторизований користувач має можливість видалити власний профіль.

a|AU5
a|Авторизований користувач
a|Перегляд історії польотів та бонусів
a|Авторизований користувач має можливість переглянути історію польотів та бонусів.

a|A1
a|Адміністратор
a|Адміністрування інформації про авіарейси
a|Адміністратор має можливість додавати нові авіарейси, корегувати інформацію про вже існуючі, а також видаляти авіарейси з бази даних.

a|A2
a|Адміністратор
a|Адміністрування інформації про користувачів
a|Адміністратор має можливість отримати інформацію по кожному з користувачів системи. За необхідності може корегувати інформацію користувача, а також заблокувати користувачу доступ до системи.

a|A3
a|Адміністратор
a|Адміністрування інформації про замовлення
a|Адміністратор має можливість отримати інформацію по кожному з замовлень в системі. За необхідності може корегувати інформацію про замовлення, а також відмінити замовлення користувача в разі потреби.

|=====================================

=== Припущення і залежності

Дана система буде використовуватися у відкритому доступі для користувачів. Але оскільки ситсема використвуватиметься з прив'язкою до певного аеропорта, то адміністратори мають бути групою співробітників аеропорту, що мають доступ до внутрішньої інформації щодо діяльності аеропорту, та підпорядковуються певному керівництву, що приймає рішення про зміни в базі системи. 

В разі розширення списку необхідноЇ інформації про авіарейси система вимагатиме незначних змін (переконфігурація бази данних та додання нової інформації). Аналогічні зміни потрібні в разі розширення списку інформації про користувача з деяким можливим доповненням: у випадку, коли нові поля будуть обов'язковими для заповнення користувачами, необхідно розробити додаткой інтерфейс шо буде сповіщувати про це користувача.

== Опис вимог

=== Короткий опис вимог

==== U1. Пошук авіарейсів за параметрами

[width="100%", options="noheader", cols="4"]
|======================================
|U1
|Користувач
|Пошук авіарейсів за параметрами
|За необхідності отримати список авіарейсів з певними параметрами, користувач може використати функцію пошуку авіаквитків.
|======================================

_Основна діюча особа_: Користувач

_Інші учасники преценденту_: відсутні

_Зв'язки з іншими прецендентами_: відсутні

_Короткий опис_:

Даний варіант використання дозволяє Користувачу отримати список авіарейсів, шо обслуговуються аеропортом та задовольняють заданим Користувачем параметрам пошуку. До параметрів пошуку входять: дата вильоту *TBD*

== Допоміжна інформація

*TBD*