
= [[entity_root.anchor]]Специфікація вимог до системи: Інформаційна система "Аеропорт"
:title-page:
Осока Данііл <osokadania@gmail.com>
0.1, 
:short-title: SRS
:toc:
:toc-title: Зміст
:toclevels: 5
:sectnums:


.Історія змін
[width="100%", options="header"]
|=====================================
|Дата|Версія|Опис|Автор

a|20.10.2021
a|0.1
a|Початкове створення
a|Осока Данііл
|=====================================

== Введення

=== Ціль

Ціль цього документу - сформулювати вимоги до інформаційної системи "Аеропорт". Дані вимоги описані в формі прецендентів, коротких описів функціональних вимог і опису нефункціональних вимог.

=== Сфера охоплення
Документ фіксує детальні вимоги до інформаційної системи "Аеропорт" для їх однозначного розуміння всіма учасниками розробки системи.

=== Визначення, акроніми та скорочення
.Визначення, акроніми та скорочення
[width="100%", options="header"]
|=====================================
|Термін|Визначення

|=====================================

=== Посилання [[references]]
Вимоги співвласників та бачення продукту наявні в документі "Технічне завдання" (TR.pdf).

=== Короткий опис системи

Інформаційна система "Аеропорт" - система, призначена для автоматизації роботи відділу продаж квитків на рейси аеропорту.

== Загальний опис

=== Огляд прецендентів

Короткий опис акторів системи:

.Актори системи
[width="100%", options="header"]
|=====================================
|Актор|Короткий опис 

a|Неавторизований користувач
a|Рядовий користувач системи, що не пройшов авторизацію. Має можливість переглянути список доступних рейсів, знайти або відфільтрувати рейси за певним набором критеріїв. Може зареєструватися в системі або/та пройти авторизацію. 

a|Авторизований користувач
a|Рядовий користувач системи, що пройшов авторизацію. Має такі самі можливості, що і неавторизований користувач, а також може придбати онлайн або забронювати квиток, має можливість переглядати історію своїх польотів і заброньовані квитки, а також може перешлядати і використовувати для накопичені бонуси.

a|Адміністратор
a|Адмініструє систему. Має можливість додавати, коректувати і видаляти інформацію про авіарейси і про користувачів.

|=====================================

Список варіантів використання:

.Реєстр варіантів використання
[width="100%", options="header"]
|=====================================
|Код|Основний актор|Найменування|Суть

a|<<U1, U1>>
a|Неавторизований користувач / Авторизований користувач
a|Пошук авіарейсів за параметрами
a|За необхідності отримати список авіарейсів з певними параметрами, користувач може використати функцію пошуку авіаквитків.

a|<<U2, U2>>
a|Неавторизований користувач / Авторизований користувач
a|Отримання інформації по авіарейсу
a|Користувач може отримати повну інформацію по конкретному авіарейсу.

a|<<NU1, NU1>>
a|Неавторизований користувач
a|Реєстрація
a|Неавторизований користувач має можливість пройти процедуру реєстрації в системі.

a|<<NU2, NU2>>
a|Неавторизований користувач
a|Авторизакія
a|Неавторизований користувач має можливість пройти процедуру авторизації в системі.

a|<<AU1, AU1>>
a|Авторизований користувач
a|Придбання або бронювання квитка
a|Авторизований користувач може забронювати квиток на обраний авіарейс, при цьому він має можливість або повністю оплатити квиток онлайн, або оплатити бронь пізніше в касі. Також користувач може використовувати бонуси як для повної, так і для часткової оплати квитків.

a|<<AU2, AU2>>
a|Авторизований користувач
a|Деавторизація
a|Авторизований користувач має можливість пройти процедуру деавторизації в системі.

a|<<AU3, AU3>>
a|Авторизований користувач
a|Редагування профілю
a|Авторизований користувач має можливість додавати, змінювати власну інформацію, а також видаляти ту власну інформацію, якщо вона не є обов'язковою.

a|<<AU4, AU4>>
a|Авторизований користувач
a|Видалення профілю
a|Авторизований користувач має можливість видалити власний профіль.

a|<<AU5, AU5>>
a|Авторизований користувач
a|Перегляд історії польотів та бонусів
a|Авторизований користувач має можливість переглянути історію польотів та бонусів.

a|<<A1, A1>>
a|Адміністратор
a|Адміністрування інформації про авіарейси
a|Адміністратор має можливість додавати нові авіарейси, корегувати інформацію про вже існуючі, а також видаляти авіарейси з бази даних.

a|<<A2, A2>>
a|Адміністратор
a|Адміністрування інформації про користувачів
a|Адміністратор має можливість отримати інформацію по кожному з користувачів системи. За необхідності може корегувати інформацію користувача, а також заблокувати користувачу доступ до системи.

a|<<A3, A3>>
a|Адміністратор
a|Адміністрування інформації про замовлення
a|Адміністратор має можливість отримати інформацію по кожному з замовлень в системі. За необхідності може корегувати інформацію про замовлення, а також відмінити замовлення користувача в разі потреби.

|=====================================

=== Припущення і залежності

Дана система буде використовуватися у відкритому доступі для користувачів. Але оскільки ситсема використвуватиметься з прив'язкою до певного аеропорта, то адміністратори мають бути групою співробітників аеропорту, що мають доступ до внутрішньої інформації щодо діяльності аеропорту, та підпорядковуються певному керівництву, що приймає рішення про зміни в базі системи. Авторизований користувач має можливість 

В разі розширення списку необхідноЇ інформації про авіарейси система вимагатиме незначних змін (переконфігурація бази данних та додання нової інформації). Аналогічні зміни потрібні в разі розширення списку інформації про користувача з деяким можливим доповненням: у випадку, коли нові поля будуть обов'язковими для заповнення користувачами, необхідно розробити додаткой інтерфейс шо буде сповіщувати про це користувача.

== Опис вимог

=== Короткий опис вимог

==== U1. Пошук авіарейсів за параметрами [[U1]]

[width="100%", options="noheader", cols="4"]
|======================================
|U1
|Неавторизований користувач / Авторизований користувач
|Пошук авіарейсів за параметрами
|За необхідності отримати список авіарейсів з певними параметрами, користувач може використати функцію пошуку авіаквитків.
|======================================

_Основна діюча особа_: Неавторизований користувач / Авторизований користувач

_Інші учасники преценденту_: відсутні

_Зв'язки з іншими прецендентами_: Включається прецедентом <<U2>>

_Короткий опис_:

Даний варіант використання дозволяє Авторизованому/Неавторизованому Користувачу отримати список авіарейсів, шо обслуговуються аеропортом та задовольняють заданим Користувачем параметрам пошуку. До параметрів пошуку входять: номер рейсу, дата та час вильоту, тривалість польоту, аеропорт прибуття, доступні Неавторизований користувач має можливість пройти процедуру реєстрації в системі. квитків.

==== U2. Отримання інформації по авіарейсу [[U2]]

[width="100%", options="noheader", cols="4"]
|======================================
|U2
|Неавторизований користувач / Авторизований користувач
|Отримання інформації по авіарейсу
|Користувач може отримати повну інформацію по конкретному авіарейсу.
|======================================

_Основна діюча особа_: Неавторизований користувач / Авторизований користувач

_Інші учасники преценденту_: відсутні

_Зв'язки з іншими прецендентами_: Включає прецедент <<U1>>

_Короткий опис_:

Даний варіант використання дозволяє Авторизованому/Неавторизованому Користувачу отримати повну інформацію по будь-якому авіарейсу, шо міститься в списку, отриманому в результаті пошуку квитків (прецедент <<U1>>). До інформації про рейс входить: номер рейсу, дата та час вильоту, тривалість польоту, аеропорт прибуття, доступні Неавторизований користувач має можливість пройти процедуру реєстрації в системі. квитків та кількість вільних квитків для кожного з класів.

==== NU1. Реєстрація [[NU1]]

[width="100%", options="noheader", cols="4"]
|======================================
|NU1
|Неавторизований користувач
|Реєстрація
|Неавторизований користувач має можливість пройти процедуру реєстрації в системі.
|======================================

_Основна діюча особа_: Неавторизований користувач

_Інші учасники преценденту_: відсутні

_Зв'язки з іншими прецендентами_: включається прецедентом <<NU2>>

_Короткий опис_:

Даний варіант використання дозволяє Неавторизованому Користувачу зареєструватися в системі. Для реєстрації в системі користувачу необхідно буде вказати ім'я та,ізвище, номер мобільного телефону, електронну пошту та пароль для подальшоа авторизаціа (прецедент <<NU2>>).

==== NU2. Авторизація [[NU2]]

[width="100%", options="noheader", cols="4"]
|======================================
|NU2
|Неавторизований користувач
|Авторизація
|Неавторизований користувач має можливість пройти процедуру авторизації в системі.
|======================================

_Основна діюча особа_: Неавторизований користувач

_Інші учасники преценденту_: відсутні

_Зв'язки з іншими прецендентами_: включає прецедентом <<NU1>>

_Короткий опис_:

Даний варіант використання дозволяє Неавторизованому Користувачу авторизуватися в системі в системі, в якій необхідно попередньо авторизуватися (прецедент <<NU1>>). Для авторизації Неавторизованому Користувачу необхідно вказати телефон/електронну пошту та пароль, що відповідають вказаним при реєстрації (прецедент <<NU1>>). Після авторизації сесія користування системою в якості даного автора закінчується, і почанається сесія Авторизованого Користувача.

==== AU1. Придбання або бронювання квитка [[AU1]]

[width="100%", options="noheader", cols="4"]
|======================================
|AU1
|Авторизований користувач
|Придбання або бронювання квитка
|Авторизований користувач може забронювати квиток на обраний авіарейс, при цьому він має можливість або повністю оплатити квиток онлайн, або оплатити бронь пізніше в касі. Також користувач може використовувати бонуси як для повної, так і для часткової оплати квитків.
|======================================

_Основна діюча особа_: Авторизований користувач

_Інші учасники преценденту_: відсутні

_Зв'язки з іншими прецендентами_: відсутній

_Короткий опис_:

Даний варіант використання дозволяє Авторизованому Користувачу забронювати квиток на обраний авіарейс, при цьому він має можливість або повністю оплатити квиток онлайн, або оплатити бронь пізніше в касі. Оплата квитка онлайн відбувається або повністю валютою, або повністю бонусами, або комбіновано у співвідношенні, заданим Авторизованим Користувачем.

==== AU2. Деавторизація [[AU2]]

[width="100%", options="noheader", cols="4"]
|======================================
|AU2
|Авторизований користувач
|Деавторизація
|Авторизований користувач має можливість пройти процедуру деавторизації в системі.
|======================================

_Основна діюча особа_: Авторизований користувач

_Інші учасники преценденту_: відсутні

_Зв'язки з іншими прецендентами_: розширюється прецедентом <<AU4>>

_Короткий опис_:

Даний варіант використання дозволяє Авторизованому Користувачу вийти з власного кабінету. Тим самим закінчити сесію користування системою в якості даного автора, і почати сесію Неавторизованого Користувача.

==== AU3. Редагування профілю [[AU3]]

[width="100%", options="noheader", cols="4"]
|======================================
|AU3
|Авторизований користувач
|Редагування профілю
|Авторизований користувач має можливість додавати, змінювати власну інформацію, а також видаляти ту власну інформацію, якщо вона не є обов’язковою.
|======================================

_Основна діюча особа_: Авторизований користувач

_Інші учасники преценденту_: відсутні

_Зв'язки з іншими прецендентами_: відсутній

_Короткий опис_:

Даний варіант використання дозволяє Авторизованому Користувачу додавати, змінювати власну інформацію, а також видаляти ту власну інформацію, якщо вона не є обов’язковою. До обов'язкової інформації входить: ім'я, прізвище, номер мобільного телефону, електронна пошта та пароль.

==== AU4. Видалення профілю [[AU4]]

[width="100%", options="noheader", cols="4"]
|======================================
|AU4
|Авторизований користувач
|Видалення профілю
|Авторизований користувач має можливість видалити власний профіль.
|======================================

_Основна діюча особа_: Авторизований користувач

_Інші учасники преценденту_: відсутні

_Зв'язки з іншими прецендентами_: розширює прецедент <<AU2>>

_Короткий опис_:

Даний варіант використання дозволяє Авторизованому Користувачу безповоротньо видалити власний профіль. В результаті видалення профілю також автоматично буде виконано деавторизацію (прецедент <<AU2>>).

==== AU5. Перегляд історії польотів та бонусів [[AU5]]

[width="100%", options="noheader", cols="4"]
|======================================
|AU5
|Авторизований користувач
|Перегляд історії польотів та бонусів
|Авторизований користувач має можливість переглянути історію польотів та бонусів.
|======================================

_Основна діюча особа_: Авторизований користувач

_Інші учасники преценденту_: відсутні

_Зв'язки з іншими прецендентами_: відсутній

_Короткий опис_:

Даний варіант використання дозволяє Авторизованому Користувачу переглянути історію польотів та бонусів. В історії польотів буде відображено всі перельоти клієнта за останній рік, а також всі заброньовані та куплені квитки на майбутні рейси.

==== A1. Адміністрування інформації про авіарейси [[A1]]

[width="100%", options="noheader", cols="4"]
|======================================
|A1
|Адміністратор
|Адміністрування інформації про авіарейси
|Адміністратор має можливість додавати нові авіарейси, корегувати інформацію про вже існуючі, а також видаляти авіарейси з бази даних.
|======================================

_Основна діюча особа_: Адміністратор

_Інші учасники преценденту_: відсутні

_Зв'язки з іншими прецендентами_: відсутній

_Короткий опис_:

Даний варіант використання дозволяє Адміністратору додавати нові авіарейси, корегувати інформацію про вже існуючі, а також видаляти авіарейси з бази даних. При чому видалення авіарейсу неможливе поки існує хоча б одне замовлення на нього.

==== A2. Адміністрування інформації про користувачів [[A2]]

[width="100%", options="noheader", cols="4"]
|======================================
|A2
|Адміністратор
|Адміністрування інформації про користувачів
|Адміністратор має можливість отримати інформацію по кожному з користувачів системи. За необхідності може корегувати інформацію користувача, а також заблокувати користувачу доступ до системи.
|======================================

_Основна діюча особа_: Адміністратор

_Інші учасники преценденту_: відсутні

_Зв'язки з іншими прецендентами_: відсутній

_Короткий опис_:

Даний варіант використання дозволяє Адміністратору отримати інформацію по кожному з користувачів системи. За необхідності може корегувати інформацію користувача, а також заблокувати користувачу доступ до системи.


==== A3. Адміністрування інформації про замовлення [[A3]]

[width="100%", options="noheader", cols="4"]
|======================================
|A3
|Адміністратор
|Адміністрування інформації про замовлення
|Адміністратор має можливість отримати інформацію по кожному з замовлень в системі. За необхідності може корегувати інформацію про замовлення, а також відмінити замовлення користувача в разі потреби.
|======================================

_Основна діюча особа_: Адміністратор

_Інші учасники преценденту_: відсутні

_Зв'язки з іншими прецендентами_: відсутній

_Короткий опис_:

Даний варіант використання дозволяє Адміністратору отримати інформацію по кожному з замовлень в системі. За необхідності може корегувати інформацію про замовлення, а також відмінити замовлення користувача в разі потреби.

=== Повні описання варіантів використання

==== Повний опис варіанту використання AU1
*TBD*

==== Діаграма прецедентів
*TBD*

=== Спеціальні вимоги

==== _Функціональність_

===== F1. Розділення функціональності акторрів

Авторизований і Неавторизований Користувачі мають певний набір спільних функціональних можливостей (вимоги <<U1>> та <<U2>>). Також кожен з цих двох акторів має можливість ставати іншим з цих двої акторів шляхом авторизації/деавторизації в системі (вимоги <<NU2>> та <<AU2>> відповідно).

Адміністратор на відмінність від перерахованих вище ролей не має спільного функціоналу з іншими акторами, а також не може ставати іншим актором при будь-яких діях.

Користувачі і Адміністратори мають окремі інтерфейси для взаємодії з системою.

===== F2. Ведення переліку доступних авіарейсів

Адміністратор має підтримувати інформацію про авіарейси в базі даних в стані, що відповідає актульній інформації про доступні авіарейси аеропорту.

===== F3. Система нарахаовником окремо.

==== _Застосовність_

===== I1. Зручність використання

Інтерфейс для Авторизованого/Неавторизованого Користувача має юути інтуїтивно зрозумілим і не вимагати попередньої підготовки до використання.

Інтерфейс для Адміністратора розрахований на підготовленого співробітника аеропорту.

===== I2. Допомога в режимі онлайн

Інтерфейс для Авторизованого/Неавторизованого Користувача має містити контактну інформацію для допомоги в режимі онлайн.

==== _Надійність_

===== R1. Доступність

Для всіх акторів система має бути доступна постійно в умовах безвідмовної роботи.

Час безвідмовної роботи системи має складати 95% на рік при умові безвідмовної роботи мережі.

===== R2. Відновлення після відмови

Час відновлення після відмови, спричиненої зовнішніми факторами (збій електропостачання, відсутність Інтернету) не має перевищувати час, необхідний для усунення фатального впливу цих факторів.

Час відновлення після відмови, спричиненої фатальним збоєм операційної системи, не має перевищувати час, необхідний для перезапуску/перевстановлення її та інших необхідних програмних засобів.

Час відновлення після відмови, спричиненої некоректними діями користувача чи адміністратора, не має перевищувати 15 хвилин. Для запобігання виникнення таких ситуацій має здійснюватися аутентифікація користувачів/адміністраторів, валідація введених даних на різних етапах обробки, а також має бути проведене тестування системи для виявлення та усунення багів, що призводять до помилок.

===== R3. Архівування бази даних

Архівування бази даних відбувається автоматично з певною періодичністю, що окремо оговорюється з замовником.

В разі потреби відновлення бази даних необхідно звернутися до команди розробників, що займаються підтримкою системи.

==== _Придатність до експлуатації_

===== E1. Оновлення версій

В разі зміни версії системи від актора не вимагається нічого, окрім оновлення веб-сторінки з інетрфейсом системи.

==== _Обмеження проектування_

===== X1. Вимоги до середи виконання

* Доступ до інтернету
* Актуальний веб-браузер (під актуальним мається на увазі браузер версії, що досі підтримується розробниками)
* оперативну пам’ять обсягом не менше 1 Гб
* відеокарту, монітор, засоби вводу (миша, клавіатура, тач-скрін тощо)

===== X2. Стек допустимих технологій

* Python, Golang
* MySQL, PgSQL, Redis (optional)
* OAuth2 + JWT/SWT
* Git
* k8s/microk8s, Docker
* React + Redux, JS/TS, CSS/SASS

== Допоміжна інформація

Перелік допоміжної інформації наявний в пункті <<references, 1.4>>