
= [[entity_root.anchor]]Специфікація вимог до системи: Інформаційна система "Аеропорт"
:title-page:
Осока Данііл <osokadania@gmail.com>
0.1, 
:short-title: SRS
:toc:
:toc-title: Зміст
:toclevels: 5
:sectnums:


.Історія змін
[width="100%", options="header"]
|=====================================
|Дата|Версія|Опис|Автор

a|20.10.2021
a|0.1
a|Початкове створення
a|Осока Данііл
|=====================================

== Введення

=== Ціль

Ціль цього документу - сформулювати вимоги до інформаційної системи "Аеропорт". Дані вимоги описані в формі прецендентів, коротких описів функціональних вимог і опису нефункціональних вимог.

=== Сфера охоплення
Документ фіксує детальні вимоги до інформаційної системи "Аеропорт" для їх однозначного розуміння всіма учасниками розробки системи.

=== Визначення, акроніми та скорочення
.Історія змін
[width="100%", options="header"]
|=====================================
|Термін|Визначення

|=====================================

=== Посилання
*TBD*

=== Короткий опис системи

Інформаційна система "Аеропорт" - система, призначена для автоматизації роботи відділу продаж квитків на рейси аеропорту.

