= [[entity_root.anchor]]Настанова користувача системи: Інформаційна система "Аеропорт"
:title-page:
Осока Данііл <osokadania@gmail.com>
0.1, 
:short-title: Manual
:toc:
:toc-title: Зміст
:toclevels: 5
:sectnums:

= Анотація

В даному документі наведено настанову користувача з експлуатації іфнормаційної системи "Аеропорт". Програмний продукт призначений для спрощення процесу придбання квитків на авіарейси, що обслуговує певний аеропорт.

В даному документі, в розділі <<P1, "Призначення програми">> наведено відомості про призначення програмного продукту та інформація, достатня для розуміння функцій програми та її експлуатації.

В розділі <<P2,"Умови виконання програми">> вказані умови, необхідні для виконання програми (мінімальний склад технічних характеристик, скалд наявного програмного забезпечення тощо).

Розділ <<P3, "Виконання програми">> даного документу вказує послідовність дій користувача, шо забезпечують ефективне використання інформаційної системи "Аеропорт". Також в даному розділі наведено опис функціоналу системи.

В розділі <<P4, "Повідомлення оператору">> даного документу наведено тексти повідомлень, що можуть бути видані користувачу системи під час взаємодії з нею, опис їх змісту і відповідні дії користувача.

Оформлення даного документу зроблено згідно зі стандартом ГОСТ 19.505–79.

== Призначення програми [[P1]]

== Умови виконання програми [[P2]]

== Виконання програми [[P3]]

== Повідомлення оператору [[P4]]